spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3307/${DB_NAME:mst_user}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:dev}
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 50
      max-wait: 10000
      test-on-borrow: true
      initial-size: 5
      min-idle: 5
      validation-query: SELECT 1
